// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using doctorWebApp.context;

#nullable disable

namespace doctorWebApp.Migrations
{
    [DbContext(typeof(doctorAppContext))]
    [Migration("20240514171620_doctor")]
    partial class doctor
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("doctorWebApp.models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Experience = 2,
                            Name = "mv",
                            Salary = 1000,
                            Specialization = "Cardio"
                        },
                        new
                        {
                            Id = 102,
                            Experience = 2,
                            Name = "vk",
                            Salary = 1500,
                            Specialization = "Neuro"
                        },
                        new
                        {
                            Id = 103,
                            Experience = 2,
                            Name = "mk",
                            Salary = 1500,
                            Specialization = "Gastro"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
